operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        getExpressAuditFileData:
          function: actions/getExpressAuditFileData/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            GENERATE_AUDIT_REPORT_LOG: $GENERATE_AUDIT_REPORT_LOG
          annotations:
            require-adobe-auth: true
            final: true
        clearExpressAuditData:
          function: actions/clearExpressAuditData/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            GENERATE_AUDIT_REPORT_LOG: $GENERATE_AUDIT_REPORT_LOG
          annotations:
            require-adobe-auth: true
            final: true
        getExpressAuditReport:
          function: actions/getExpressAuditReport/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            GENERATE_AUDIT_REPORT_LOG: $GENERATE_AUDIT_REPORT_LOG
          annotations:
            require-adobe-auth: true
            final: true
        getAemFileExpressAudit:
          function: actions/getAemFileExpressAudit/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            GENERATE_AUDIT_REPORT_LOG: $GENERATE_AUDIT_REPORT_LOG
          annotations:
            require-adobe-auth: true
            final: true
        get-auth:
          function: actions/get-auth/index.js
          web: 'no'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            IMS: $IMS_ENDPOINT
          annotations:
            require-adobe-auth: false
            final: true
        getAemAssetData:
          function: actions/getAemAssetData/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
          annotations:
            require-adobe-auth: true
            final: true
        getAemPresignedUrl:
          function: actions/getAemPresignedUrl/index.js
          web: 'no'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
          annotations:
            require-adobe-auth: true
            final: true
        onAemProcComplete:
          function: actions/onAemProcComplete/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            NEW_RELIC_LICENSE_KEY: $NEW_RELIC__LICENSE_KEY
            NEW_RELIC_LOG_LEVEL: $NEW_RELIC_LOG_LEVEL
            NEW_RELIC_ACCOUNT_ID: $NEW_RELIC_ACCOUNT_ID    
          annotations:
            require-adobe-auth: false
            final: true
        onPsApiProcComplete:
          function: actions/onPsApiProcComplete/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            GENERATE_AUDIT_REPORT_LOG: $GENERATE_AUDIT_REPORT_LOG
          annotations:
            require-adobe-auth: false
            final: true
        getPhotoshopManifestForPresignedUrl:
          function: actions/getPhotoshopManifestForPresignedUrl/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_ID
            AEM_SERVICE_TECH_ACCOUNT_ID: $AEM_SERVICE_TECH_ACCOUNT_ID
            AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET: $AEM_SERVICE_TECH_ACCOUNT_CLIENT_SECRET
            AEM_SERVICE_TECH_ACCOUNT_ORG_ID: $AEM_SERVICE_TECH_ACCOUNT_ORG_ID
            AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY: $AEM_SERVICE_TECH_ACCOUNT_PRIVATE_KEY
            AEM_SERVICE_TECH_ACCOUNT_META_SCOPES: $AEM_SERVICE_TECH_ACCOUNT_META_SCOPES
            AEM_USE_PASSED_AUTH: $GET_AEM_ASSET_DATA__AEM_USE_PASSED_AUTH
            FIREFLY_SERVICES_ORG_ID: $FIREFLY_SERVICES_ORG_ID
            FIREFLY_SERVICES_CLIENT_ID: $FIREFLY_SERVICES_CLIENT_ID
            FIREFLY_SERVICES_USE_PASSED_AUTH: $FIREFLY_SERVICES__USE_PASSED_AUTH
            FIREFLY_SERVICES_CLIENT_SECRET: $FIREFLY_SERVICES_CLIENT_SECRET
            FIREFLY_SERVICES_SCOPES: $FIREFLY_SERVICES_SCOPES
            NEW_RELIC_LICENSE_KEY: $NEW_RELIC__LICENSE_KEY
            NEW_RELIC_LOG_LEVEL: $NEW_RELIC_LOG_LEVEL
            NEW_RELIC_ACCOUNT_ID: $NEW_RELIC_ACCOUNT_ID 
          annotations:
            require-adobe-auth: true
            final: true